# 开发用极简训练配置（使用合成数据）

data:
  metadata_path: "data/metadata.csv"
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  labeled_dir: "data/labeled"
  image_dir: "data/processed"
  batch_size: 4
  num_workers: 0
  val_split: 0.2
  test_split: 0.1
  target_size: [224, 224]

preprocessing:
  target_size: [224, 224]
  denoise: false
  normalize: false
  roi_method: "fixed"

model:
  backbone_type: "vit"
  backbone_name: "vit_tiny_patch16_224"
  pretrained: false
  freeze_layers: false
  use_attention: false
  num_classes: 4
  num_params: 4
  num_defect_types: 5

optimizer:
  name: "adamw"
  learning_rate: 0.001
  weight_decay: 0.0001
  momentum: 0.9

scheduler:
  name: "cosine"
  step_size: 10
  gamma: 0.1
  t_max: 10
  factor: 0.1
  patience: 3
  verbose: true

loss:
  name: "dynamic"
  task_weights:
    quality: 1.0
    params: 1.0
    defects: 1.0
  temp: 2.0

num_epochs: 1
checkpoint_path: ""
output_dir: "models/checkpoints_dev"
use_gpu: false
use_amp: false
gradient_clip: true
gradient_clip_value: 1.0
print_freq: 5
save_freq: 1
seed: 123

